
/**
* AnnuaireOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Annuaire.idl
* mercredi 8 avril 2015 16 h 14 CEST
*/

public interface AnnuaireOperations 
{
  void chercheNom (String nom, org.omg.CORBA.StringHolder numero);
  void listerNoms (org.omg.CORBA.StringHolder liste);
} // interface AnnuaireOperations
