
/**
* iorfile.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Annuaire.idl
* mercredi 8 avril 2015 16 h 14 CEST
*/

public interface iorfile
{
  public static final String value = "annu.ior";
}
