
/**
* OpMatrice.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OpMatrice.idl
* mardi 7 avril 2015 09 h 03 CEST
*/

public interface OpMatrice extends OpMatriceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface OpMatrice
