package Comptes;


/**
* Comptes/Compte.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Comptes.idl
* lundi 27 avril 2015 18 h 56 CEST
*/

public interface Compte extends CompteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Compte
