package Comptes;


/**
* Comptes/CompteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Comptes.idl
* lundi 27 avril 2015 18 h 56 CEST
*/

public interface CompteOperations 
{
  double somme ();
  void deposeBillets (double montant);
  boolean retireBillets (double montant);
  double afficheMontant ();
  boolean virementCompteaCompte (double somme, Comptes.Compte cpt);
} // interface CompteOperations
